# Generated by Django 3.0.7 on 2020-06-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200607_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cat',
        ),
    ]
